"""
Background worker that polls for APPROVED scripts and generates videos.

Can be run as a standalone process alongside the API server.
Run with: python -m app.worker.generator
"""
import os
import sys
import time
import asyncio
import logging
from datetime import datetime, timezone

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))

from app.database import SessionLocal, Script, ScriptStatus
from app.audio.tts import TTSEngine
from app.video.background import PexelsClient, VideoSourceRouter
from app.video.captions import CaptionGenerator
from app.render.composer import VideoComposer, CompositionConfig, CaptionSegment
from app.render.thumbnail import ThumbnailGenerator
from app.upload.youtube import YouTubeUploader
from app.config import settings

logger = logging.getLogger(__name__)


class VideoGeneratorWorker:
    def __init__(self):
        self.tts = TTSEngine()
        self.video_sources = VideoSourceRouter.from_settings()
        self.captions = CaptionGenerator(settings.whisper_model)
        self.composer = VideoComposer()
        self.thumbnail = ThumbnailGenerator()
        self.uploader = YouTubeUploader()
        self.running = True

    def process_script(self, script: Script):
        import random
        from datetime import datetime, timezone
        import os as os_mod

        script_id = script.id
        safe_title = "".join(c for c in script.title if c.isalnum() or c in " _-")[:30].strip()

        # 1. Generate TTS
        audio_path = os_mod.path.join(settings.data_dir, "audio", f"{script_id}.mp3")
        os_mod.makedirs(os_mod.path.dirname(audio_path), exist_ok=True)
        asyncio.run(self.tts.generate(script.content, audio_path))
        duration = self.tts.get_duration(audio_path) + 1.0

        if duration > settings.max_video_duration:
            logger.warning(f"Script too long: {duration}s, max is {settings.max_video_duration}s")
            return False

        # 2. Generate captions
        segs = self.captions.generate(audio_path)

        # 3. Fetch background video (tries Pexels → Pixabay → Coverr → Pollinations AI)
        bg_path = os_mod.path.join(settings.data_dir, "downloads", f"{script_id}_bg.mp4")
        os_mod.makedirs(os_mod.path.dirname(bg_path), exist_ok=True)
        bg_result = self.video_sources.search_and_download(
            query=safe_title or "nature",
            output_path=bg_path,
            min_duration=duration,
        )
        if not bg_result:
            bg_path = None

        # 4. Compose video
        output_path = os_mod.path.join(settings.data_dir, "videos", f"{script_id}.mp4")
        os_mod.makedirs(os_mod.path.dirname(output_path), exist_ok=True)

        # Select random music track if configured
        music_path = None
        music_dir = os_mod.path.join(settings.data_dir, "..", "app", "assets", "music")
        if os_mod.path.exists(music_dir):
            tracks = [f for f in os_mod.listdir(music_dir) if f.endswith((".mp3", ".wav"))]
            if tracks:
                music_path = os_mod.path.join(music_dir, random.choice(tracks))

        cfg = CompositionConfig(
            background_video_path=bg_path if (bg_path and os_mod.path.exists(bg_path)) else None,
            audio_path=audio_path,
            captions=segs,
            output_path=output_path,
            duration=duration,
            caption_position=settings.caption_position,
            music_path=music_path,
        )
        self.composer.compose(cfg)

        # 5. Generate thumbnail
        thumb_path = os_mod.path.join(settings.data_dir, "thumbnails", f"{script_id}.jpg")
        self.thumbnail.generate(script.title, thumb_path)

        # 6. Upload to YouTube
        tags_list = (script.tags or "").split(",") if script.tags else [script.title]
        video_id = self.uploader.upload(
            video_path=output_path,
            title=script.title,
            description=script.description or f"#shorts {script.title}\n\nAuto-generated by YT Shorts Engine",
            tags=[t.strip() for t in tags_list],
            thumbnail_path=thumb_path,
        )

        return video_id

    def run_once(self):
        db = SessionLocal()
        try:
            scripts = db.query(Script).filter(
                Script.status == ScriptStatus.APPROVED
            ).order_by(Script.created_at.asc()).limit(1).all()

            for script in scripts:
                script.status = ScriptStatus.GENERATING
                db.commit()

                try:
                    video_id = self.process_script(script)
                    if video_id:
                        script.youtube_video_id = video_id
                        script.status = ScriptStatus.UPLOADED
                        script.uploaded_at = datetime.now(timezone.utc)
                        logger.info(f"Success: {script.title} -> https://youtu.be/{video_id}")
                    else:
                        script.status = ScriptStatus.FAILED
                        logger.warning(f"Failed to generate/upload: {script.title}")
                except Exception as e:
                    script.status = ScriptStatus.FAILED
                    logger.error(f"Error processing {script.id}: {e}")

                db.commit()
        finally:
            db.close()

    def run_forever(self, poll_interval: int = 60):
        logger.info(f"Worker started, polling every {poll_interval}s")
        while self.running:
            try:
                self.run_once()
            except Exception as e:
                logger.error(f"Worker error: {e}")
            time.sleep(poll_interval)

    def stop(self):
        self.running = False


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    worker = VideoGeneratorWorker()
    worker.run_forever(poll_interval=30)
